# Generated by Django 5.0.6 on 2024-05-26 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('china', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='china',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='china',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='china.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='china',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='china.tagpost', verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='china',
            name='translate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_in_rus', to='china.translate', verbose_name='Перевод'),
        ),
        migrations.AddIndex(
            model_name='china',
            index=models.Index(fields=['-time_create'], name='china_china_time_cr_7724b4_idx'),
        ),
    ]
