# Generated by Django 5.0.6 on 2024-05-21 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0019_remove_china_image_alter_china_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='china',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cats', to='china.category', verbose_name='Категории'),
        ),
    ]
